name: Build and push images

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build images
      run: make build

    - name: Test images
      run: make test

    - name: Publish images
      run: make push
