name: Build and push images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build images
      run: make build
