name: Test PR

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build images
      run: make build

    - name: Test images
      run: make test
